name = "sugar-and-spice"
license = "GPLv3"
licenselink = "https://github.com/thedeetch/sugar-and-spice/blob/master/LICENSE"
description = "Sugar and Spice is chic, feminine theme created with wedding blogs and wedding industry in mind."
tags = ["blog"]
features = ["blog", "themes"]
min_version = 0.62

# TODO: Remove below when renaming to theme.toml
title = "Midwest Mash"

[author]
    name = "thedeetch"
    homepage = "https://thedeetch.github.io"

# Original Wordpress theme
[original]
    author = "Aleksandra Łączek"
    homepage = "http://webtuts.pl/themes/sugar-spice"
    repo = "https://themes.svn.wordpress.org/sugar-and-spice/"

[params]
	description = "Dishing on Food and Life from my home to yours"

	main_color = "emerald"
	accent_color = "peach"
	pinterestUrl = "https://www.pinterest.com/tgoltz/pins/"
	instagramUrl = "https://instagram.com/midwest.mash/"
	facebookUrl = "https://facebook.com/midwestmash"
	aboutMeImage = "https://midwestmash.com/wp-content/uploads/2016/10/Nick-and-Traci-All-Photos-0522.jpg"
	summary = "Iowa girl turned Colorado transplant. Self-proclaimed home chef and mama to two little boys. Exploring food and embracing motherhood daily.  For collaborations please e-mail me at traci.dietrich@gmail.com"

[menu]
  [[menu.main]]
    name = "About Me"
    url = ""
    weight = -1

  [[menu.main]]
    name = "Mom Blog"
    url = "tags/mom-blog"
    weight = 1

  [[menu.main]]
    name = "Main Dish"
    url = "tags/main-dish"
    weight = 2

  [[menu.main]]
    name = "Side Dish"
    url = "tags/side-dish"
    weight = 3

  [[menu.main]]
    name = "30 Minute Meals"
    url = "tags/30-minute-meals"
    weight = 4

  [[menu.main]]
    name = "Sandwiches"
    url = "tags/sandwiches"
    weight = 5

  [[menu.main]]
    name = "Soup"
    url = "tags/soup"
    weight = 6

  [[menu.main]]
    name = "Baked Goods"
    url = "tags/baked-goods"
    weight = 7

  [[menu.main]]
    name = "Cookies"
    url = "tags/cookies"
    weight = 8

  [[menu.main]]
    name = "Toddler Treats"
    url = "tags/toddler-treats"
    weight = 9
